# Data Science Tools and Ecosystem

In this notebook, Data Science Tools and Ecosystem are summarized.

**Objectives:**
- List popular languages for Data Science
- List commonly used libraries by Data Scientists
- List common Data Science tools
- Evaluate arithmetic expressions in Python

Some of the popular languages that Data Scientists use are:

1. Python
2. R
3. Scala
4. Java
5. C/C++

Some of the commonly used libraries used by Data Scientists include:

1. Pandas
2. NymPy
3. Scikit-Learn
4. SciPy
5. Matplotlib

|**Data Science Tools**|
|-------------------------|
|Jupyter Notebook|
|VSCode with Python Libraries|
|RStudio|

### Below are a few examples of evaluating arithmetic expressions in Python

This a simple arithmetic expression to mutiply then add integers.

In [1]:
(3*4)+5

17

This will convert 200 minutes to hours by diving by 60.

In [3]:
200/60

3.3333333333333335

## Author

Anjana Kaku